### ISSUE TITLE
Delete ParseFile Cloud Function

### ISSUE THREAD

**Issue by progrmor** [ParsePlatform/CloudCode-Express#9]
I've been trying to delete a ParseFile with the Rest API for months now. Nothing works.
This is what I'm trying "at the moment". I've heard I must use the generated name url for the File and not the one I set myself. 
I think this might be the issue. Cause the delete goes through without error but doesn't delete the file.
So how do I fetch the generated name of the file with Parse's JavaScript API? 

`Parse.Cloud.define("deleteFile1", function(request, response) {
	var image1 = ...
  Parse.Cloud.httpRequest({
  url: "https://api.parse.com/1/files/" + image1.url(),
  method: 'DELETE',
  headers: {
    'X-Parse-Application-Id': '****',
    'X-Parse-Master-Key':     '****'
  }
}).then(function(httpResponse) {
    response.success("Success" + httpResponse.status);
}, function(httpResponse) {
    response.error("Failed" + httpResponse.status);
});
});`

**Comment by gfosco** [comment]
It would be the "name" field on the Parse File that you use here.  If you retrieved the file from a Parse Object, you can call the `.name()` method instead of `.url()` and it should work.  

When you upload a Parse File, the response contains the name and url fields.  As shown in the 3rd code block formatted section down from here:  https://parse.com/docs/rest/guide#files-uploading-files
